name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  push: {branches: ["master", "main"]}
  workflow_dispatch: #To make it possible to start the action manually
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: classic
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_followup: yes
          plugin_isocalendar: no
          filename: pictures/metrics.svg
          optimize: no
          config_timezone: DE
          plugin_stars: yes
          plugin_stars_limit: 2 # Limit to two entries
          plugin_lines: yes
